services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: rosterdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app-network
    # Ressourcen begrenzen (OOM auf VM)
    deploy:
      resources:
        limits:
          memory: 1G

  backend:
    build:
      context: ./backend
      network: host
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=${JWT_SECRET}

      # Datenbank-Verbindung
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rosterdb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network
    # Begrenzt den Container auf max 1GB RAM (Java nimmt sich max 512MB davon)
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    build:
      context: ./frontend
      network: host
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1 # geaendert für Docker-Version vom VM
    container_name: cadvisor
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
    ports:
      - "8081:8080" # Erreichbar über Port 8081, da Backend 8080 nutzt
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - app-network
    devices:
      - /dev/kmsg

volumes:
  db-data:

networks:
  app-network:
    driver: bridge